apiVersion: v1
kind: Secret
metadata:
  name: simple-superset-credentials
type: superset.stackable.tech/superset-credentials
stringData:
  adminUser.username: admin
  adminUser.firstname: Superset
  adminUser.lastname: Admin
  adminUser.email: admin@superset.com
  adminUser.password: admin
