apiVersion: v1
kind: Service
metadata:
  name: superset-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: superset
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 30088
