apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: superset-operator
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - list
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - command.superset.stackable.tech
    resources:
      - inits
      - restarts
      - starts
      - stops
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - command.superset.stackable.tech
    resources:
      - inits/status
    verbs:
      - patch
  - apiGroups:
      - superset.stackable.tech
    resources:
      - supersetclusters
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - superset.stackable.tech
    resources:
      - supersetclusters/status
    verbs:
      - patch
